owner: datalogics
repo: pdfRest-Status-Page
sites:
  - name: PDF Toolkit
    url: $STATUS_URL
    headers:
      - "wsn: $WSN_STATUS"
  - name: PDF Forms Pro
    url: $STATUS_URL
    headers:
      - "wsn: $WSN_STATUS_FORMS"
assignees:
  - datalogics-deh
status-website:
  cname: status.pdfrest.com
  logoUrl: https://cdn.statically.io/gh/datalogics/pdfRest-Status-Page/667e9205/assets/pdfRest_submark_350_250.png
  name: pdfRest Cloud API Uptime Status
  favicon: https://cdn.statically.io/gh/datalogics/pdfRest-Status-Page/667e9205/assets/pdfrest_favicon.ico
  introTitle: "**pdfRest Cloud API Uptime Status**"
  introMessage: Average response time is the interval it takes to receive, process, and return a response to API calls for each endpoint. Processing typically accounts for a majority of this time.
  navbar:
    - title: Status
      href: /
    - title: pdfRest
      href: https://pdfRest.com
  themeUrl: https://cdn.statically.io/gh/datalogics/pdfRest-Status-Page/667e9205/assets/theme.css
